# Use an official Node.js image.
FROM node:23.6.0

# Set the working directory.
WORKDIR /server
COPY ./package.json /server
RUN npm install

# Copy package files and install dependencies.
COPY ./backend/ /server

# Copy the rest of your application code.
# Expose the port Vite is running on.
EXPOSE 81

# Run the dev server.
CMD ["npm", "run", "server-docker"]